### ISSUE TITLE
Enable tooltips in MaRDI Query Service

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#536]
**New feature description in words**:

When hovering over Wikibase identifiers in other instances, the user is given a [tooltip](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help/SPARQL_Editor/en#Tooltip) displaying the corresponding label, e.g. as shown here:
![image](https://github.com/MaRDI4NFDI/portal-compose/assets/465923/cae1b3de-9a63-4b2b-873d-8a374dd319db)
 
**TODOS**: 
-  I'm not sure how to enable/ disable this, but the relevant code seems to be at https://gerrit.wikimedia.org/g/wikidata/query/gui/+/8a1b99d433396806d4ee8c099dbfbf74a7da35b5/wikibase/queryService/ui/editor/tooltip/Rdf.js

**Considered Alternatives**: 
- The alternative would be to keep the status quo, which makes it hard to work with our endpoint.

**Checklist for this issue**: 

- [X] Participants in discussion have been invited as assignees 
- [X] All fields of the issue have been filled 
- [X] Example fields have been removed
- [X] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
It seems to be blocked due to wrong CORS headers.

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://portal.mardi4nfdi.de/w/api.php?origin=*&action=wbsearchentities&format=json&limit=50&continue=0&language=de&uselang=de&search=P31&type=property. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200.

**Comment by physikerwelt** [comment]
A quick workaround is to install (and enable https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/ ) At least this works for me.

@eloiferrer can you maybe look for a general solution?

**Comment by eloiferrer** [comment]
I think this is a problem with our docker configuration. At the beginning of mardi, I spent already some time trying to fix it but did not succeed. I will have a look again. Just for reference, the issue was also described here:
https://github.com/MaRDI4NFDI/portal-compose/issues/35
https://phabricator.wikimedia.org/T299067

**Comment by physikerwelt** [comment]
Sorry, I wanted to reference this in a PR but not to close it. I am no deploying to staging for testing

**Comment by physikerwelt** [comment]
Now, it works on staging. I'll try to deploy it to production.

**Comment by physikerwelt** [comment]
works now

**Comment by Daniel-Mietchen** [comment]
@physikerwelt The problem has returned a few days ago - not sure what the trigger was.

**Comment by eloiferrer** [comment]
Not sure what is going on, just wanted to note that it works in staging https://query.staging.mardi4nfdi.org/ which in principle uses the same exact configuration

**Comment by physikerwelt** [comment]
In production, I see a 502 for https://query.portal.mardi4nfdi.de/proxy/wikibase/w/api.php?origin=*&action=query&meta=siteinfo&format=json&siprop=languages On staging, I see no examples (which were there before). I always used the cat example for testing.

**Comment by eloiferrer** [comment]
I fixed this a couple weeks ago but I was waiting for a new deployment to see if it would break. Since it is still working after the deployment from yesterday I consider this tentatively solved.
