### ISSUE TITLE
Property that connects research problem with statistical model (different description of existing property on wikidata)

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#542]
Hello,

this issue is connected to the issue https://github.com/MaRDI4NFDI/portal-compose/issues/541. We would like to have a property which in a KG connects "Research Problem" to a "Statistical model". One option we could use is as described in https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/40. Another option is to use property "represented by". The latter property has its homonymic [analogue](https://www.wikidata.org/wiki/Property:P1875) on the wikidata , but this property has another concept in mind to that the one that we need (it stays for " ..person or agency that represents or manages the subject" but we need it to be in the sense ".. conveys the information in the subject and enables intelligent-like decision based on statistical model"). 

It is possible to have  the same property "represented by" but with a different semantic meaning as a property on portal/wikidata? 

Thank you.

**Comment by eloiferrer** [comment]
I think it would be better to avoid using the label 'represented by' since this can create misunderstandings with the already existing property in Wikidata. I would suggest just creating one property called 'modeled by'. The same property pointing in the opposite direction (models) is redundant and should not be created. Would that work for you @OleksandrZadorozhnyiML?

Any other thing we should consider @Daniel-Mietchen? Otherwise I would go ahead and create the property.

**Comment by OleksandrZadorozhnyiML** [comment]
> ... Would that work for you @OleksandrZadorozhnyiML?
> 
@eloiferrer  Yes, I think it is good. Only one minor issue: I would suggest then to use "modelled by" (double "l", British English) instead of "modeled by"( one "l", US English) to keep it somehow consistent (I assume that items/names on portal/wikidata are in British English, however I am not sure).

**Comment by eloiferrer** [comment]
I have created the property: https://portal.mardi4nfdi.de/wiki/Property:P1513

@OleksandrZadorozhnyiML feel free to change the description if you have a formulation that would be more accurate.
