### ISSUE TITLE
Show a warning, when a paper title can not be shown due to license restrictions

### ISSUE THREAD

**Issue by OleksandrZadorozhnyiML** [MaRDI4NFDI/portal-compose#558]
Hello,

I noticed that there are some unnamed publications on the portal which are attached to the profile of scientist. What I mean is that there is a link to an item, but an item comes without a title (see for example [this publication](https://portal.mardi4nfdi.de/wiki/Publication:5053287) of [this researcher](https://portal.mardi4nfdi.de/wiki/Person:80803) or [this publication](https://portal.mardi4nfdi.de/wiki/Publication:4372451) of [this researcher](https://portal.mardi4nfdi.de/wiki/Person:239394) ). 

Is it possible/realistic to fix this? Thank you.

**Comment by eloiferrer** [comment]
Hi @OleksandrZadorozhnyiML,

Thanks for the comment. Part of the publication metadata we have in the knowledge graph has been imported from zbMATH. Unfortunately, due to licensing issues, the metadata for some publications is released by zbMATH without the title. We decided to import those publications anyway, hoping that we will eventually be able to find the title from other sources. This has been partially happening already. For instance, obtaining the title from arXiv or from Wikidata. 

We keep working on it and the situation will slowly improve, but it is hard to guarantee whether we will be able to fill all the missing titles. A similar issue happens for some author items, for which we have an identifier but not the string name.

**Comment by physikerwelt** [comment]
Also, zbMATH Open is constantly working on being able to provide the titles.
I suggest we display something like 

> zbMATH Open Web Interface contents unavailable due to conflicting licenses.

cc @rank-zero @timconrad  what do you think?

**Comment by physikerwelt** [comment]
done
![image](https://github.com/user-attachments/assets/850fc739-2c52-42e7-afee-ec11819e61d4)
